import type {Dictionary} from "@blocknote/core";
import {en} from "@blocknote/core/locales";

/**
 * Hungarian texts of the BlockNote editor (BlockNote ships no Hungarian locale). Keys the app
 * never shows (comments, suggestions) keep the English base.
 */
export const hu: Dictionary = {
  ...en,
  slash_menu: {
    ...en.slash_menu,
    heading: {title: "Címsor 1", subtext: "Fő címsor", aliases: ["h", "h1", "cim", "címsor"], group: "Címsorok"},
    heading_2: {title: "Címsor 2", subtext: "Fejezet címe", aliases: ["h2", "alcim", "alcím"], group: "Címsorok"},
    heading_3: {title: "Címsor 3", subtext: "Alfejezet címe", aliases: ["h3", "alcim", "alcím"], group: "Címsorok"},
    heading_4: {title: "Címsor 4", subtext: "Kisebb alcím", aliases: ["h4"], group: "További címsorok"},
    heading_5: {title: "Címsor 5", subtext: "Kis alcím", aliases: ["h5"], group: "További címsorok"},
    heading_6: {title: "Címsor 6", subtext: "Legkisebb alcím", aliases: ["h6"], group: "További címsorok"},
    toggle_heading: {title: "Lenyitható címsor 1", subtext: "Összecsukható fő címsor", aliases: ["h1", "lenyithato"],
      group: "További címsorok"},
    toggle_heading_2: {title: "Lenyitható címsor 2", subtext: "Összecsukható fejezetcím", aliases: ["h2", "lenyithato"],
      group: "További címsorok"},
    toggle_heading_3: {title: "Lenyitható címsor 3", subtext: "Összecsukható alfejezet", aliases: ["h3", "lenyithato"],
      group: "További címsorok"},
    quote: {title: "Idézet", subtext: "Idézet vagy kiemelt részlet", aliases: ["idezet", "quote", "vallomas"], group: "Alapblokkok"},
    toggle_list: {title: "Lenyitható lista", subtext: "Elrejthető tartalmú elemek", aliases: ["lista", "lenyithato"],
      group: "Alapblokkok"},
    numbered_list: {title: "Számozott lista", subtext: "Sorszámozott elemek", aliases: ["ol", "lista", "szamozott"],
      group: "Alapblokkok"},
    bullet_list: {title: "Felsorolás", subtext: "Pontokba szedett elemek", aliases: ["ul", "lista", "felsorolas"],
      group: "Alapblokkok"},
    check_list: {title: "Teendőlista", subtext: "Kipipálható elemek", aliases: ["teendo", "checklist", "pipa"],
      group: "Alapblokkok"},
    paragraph: {title: "Bekezdés", subtext: "Normál szöveg", aliases: ["p", "szoveg", "bekezdes"], group: "Alapblokkok"},
    code_block: {title: "Kódblokk", subtext: "Formázott kód", aliases: ["kod", "code"], group: "Alapblokkok"},
    page_break: {title: "Oldaltörés", subtext: "Nyomtatásnál új oldal", aliases: ["oldal", "tores"], group: "Alapblokkok"},
    table: {title: "Táblázat", subtext: "Szerkeszthető cellák", aliases: ["tabla", "táblázat"], group: "Haladó"},
    image: {title: "Kép", subtext: "Átméretezhető kép felirattal", aliases: ["kep", "kép", "foto", "image"], group: "Média"},
    video: {title: "Videó", subtext: "Beágyazott videó", aliases: ["video"], group: "Média"},
    audio: {title: "Hang", subtext: "Beágyazott hangfelvétel", aliases: ["hang", "audio"], group: "Média"},
    file: {title: "Fájl", subtext: "Beágyazott fájl", aliases: ["fajl", "file"], group: "Média"},
    emoji: {title: "Emoji", subtext: "Emoji keresése és beszúrása", aliases: ["emoji"], group: "Egyéb"},
    divider: {title: "Elválasztó", subtext: "Vízszintes vonal", aliases: ["hr", "vonal", "elvalaszto"], group: "Alapblokkok"},
  },
  placeholders: {
    ...en.placeholders,
    default: "Írj, vagy nyomd meg a „/” gombot a blokkokhoz és a „@” gombot a hivatkozásokhoz",
    heading: "Címsor",
    toggleListItem: "Lenyitható elem",
    bulletListItem: "Lista",
    numberedListItem: "Lista",
    checkListItem: "Teendő",
  },
  file_blocks: {
    ...en.file_blocks,
    add_button_text: {image: "Kép hozzáadása", video: "Videó hozzáadása", audio: "Hang hozzáadása", file: "Fájl hozzáadása"},
  },
  toggle_blocks: {add_block_button: "Üres elem. Kattints egy blokk hozzáadásához."},
  side_menu: {add_block_label: "Blokk hozzáadása", drag_handle_label: "Blokk menü"},
  drag_handle: {
    delete_menuitem: "Törlés",
    colors_menuitem: "Színek",
    header_row_menuitem: "Fejléc sor",
    header_column_menuitem: "Fejléc oszlop",
  },
  table_handle: {
    delete_column_menuitem: "Oszlop törlése",
    delete_row_menuitem: "Sor törlése",
    add_left_menuitem: "Oszlop balra",
    add_right_menuitem: "Oszlop jobbra",
    add_above_menuitem: "Sor fölé",
    add_below_menuitem: "Sor alá",
    split_cell_menuitem: "Cella felosztása",
    merge_cells_menuitem: "Cellák egyesítése",
    background_color_menuitem: "Háttérszín",
  },
  suggestion_menu: {no_items_title: "Nincs találat"},
  color_picker: {
    text_title: "Szöveg",
    background_title: "Háttér",
    colors: {
      default: "Alap", gray: "Szürke", brown: "Barna", red: "Piros", orange: "Narancs", yellow: "Sárga", green: "Zöld",
      blue: "Kék", purple: "Lila", pink: "Rózsaszín",
    },
  },
  formatting_toolbar: {
    ...en.formatting_toolbar,
    bold: {tooltip: "Félkövér", secondary_tooltip: "Mod+B"},
    italic: {tooltip: "Dőlt", secondary_tooltip: "Mod+I"},
    underline: {tooltip: "Aláhúzott", secondary_tooltip: "Mod+U"},
    strike: {tooltip: "Áthúzott", secondary_tooltip: "Mod+Shift+S"},
    code: {tooltip: "Kód", secondary_tooltip: ""},
    colors: {tooltip: "Színek"},
    link: {tooltip: "Hivatkozás", secondary_tooltip: "Mod+K"},
    file_caption: {tooltip: "Felirat szerkesztése", input_placeholder: "Felirat szerkesztése"},
    file_replace: {tooltip: {image: "Kép cseréje", video: "Videó cseréje", audio: "Hang cseréje", file: "Fájl cseréje"}},
    file_rename: {
      tooltip: {image: "Kép átnevezése", video: "Videó átnevezése", audio: "Hang átnevezése", file: "Fájl átnevezése"},
      input_placeholder: {image: "Kép neve", video: "Videó neve", audio: "Hang neve", file: "Fájl neve"},
    },
    file_download: {tooltip: {image: "Kép letöltése", video: "Videó letöltése", audio: "Hang letöltése", file: "Fájl letöltése"}},
    file_delete: {tooltip: {image: "Kép törlése", video: "Videó törlése", audio: "Hang törlése", file: "Fájl törlése"}},
    file_preview_toggle: {tooltip: "Előnézet be/ki"},
    nest: {tooltip: "Behúzás", secondary_tooltip: "Tab"},
    unnest: {tooltip: "Behúzás vissza", secondary_tooltip: "Shift+Tab"},
    align_left: {tooltip: "Balra igazítás"},
    align_center: {tooltip: "Középre igazítás"},
    align_right: {tooltip: "Jobbra igazítás"},
    align_justify: {tooltip: "Sorkizárás"},
    table_cell_merge: {tooltip: "Cellák egyesítése"},
    comment: {tooltip: "Megjegyzés"},
  },
  file_panel: {
    upload: {
      title: "Feltöltés",
      file_placeholder: {image: "Kép feltöltése", video: "Videó feltöltése", audio: "Hang feltöltése", file: "Fájl feltöltése"},
      upload_error: "Hiba: a feltöltés nem sikerült",
    },
    embed: {
      title: "Hivatkozás",
      embed_button: {image: "Kép beágyazása", video: "Videó beágyazása", audio: "Hang beágyazása", file: "Fájl beágyazása"},
      url_placeholder: "Webcím",
    },
  },
  link_toolbar: {
    delete: {tooltip: "Hivatkozás törlése"},
    edit: {text: "Szerkesztés", tooltip: "Szerkesztés"},
    open: {tooltip: "Megnyitás új lapon"},
    form: {title_placeholder: "Szöveg", url_placeholder: "Webcím"},
  },
  generic: {ctrl_shortcut: "Ctrl", form_submit: "OK"},
};
