import {expect, test} from "@playwright/test";
import {login, mockSupabase, testProfile} from "./support/mock-supabase";

/**
 * Opens every route as a high-ranking member (so admin-only UI renders too) and fails on
 * uncaught exceptions or React error screens. Data is mostly empty: this catches crashes,
 * not layout details.
 */
const ROUTES: {path: string; text: RegExp}[] = [
  {path: "/dashboard", text: /Gyors elérés/i},
  {path: "/notifications", text: /Kommunikáció/i},
  {path: "/notifications?view=settings", text: /Asztali értesítések/i},
  {path: "/reports", text: /jelentés/i},
  {path: "/reports?tab=folder", text: /jelentési mappa nyitása/i},
  {path: "/reports?tab=list", text: /Csak a sajátjaim/i},
  {path: "/reports?tab=mine", text: /Csak a sajátjaim/i},
  {path: "/reports?tab=summary", text: /tag írt jelentést/i},
  {path: "/reports/00000000-0000-4000-8000-000000000999", text: /A jelentés nem nyitható meg/i},
  {path: "/hr", text: /Human Resources/i},
  {path: "/hr?tab=requests", text: /Regisztrációk/i},
  {path: "/hr?tab=history", text: /Állományváltozások/i},
  {path: "/hr?tab=stats", text: /Rendfokozatok/i},
  {path: "/mcb", text: /Major Crimes Bureau/i},
  {path: "/mcb/suspects", text: /Bűnügyi nyilvántartás/i},
  {path: "/mcb/warrants", text: /Elbírálásra vár/i},
  {path: "/mcb/admin", text: /Az iroda vezetése/i},
  {path: "/exams", text: /Vizsgák, eredmények és javítás/i},
  {path: "/exams?tab=grading", text: /Javításra vár/i},
  {path: "/exams?tab=all_history", text: /Minden állapot/i},
  {path: "/exams?tab=trash", text: /Törölt vizsgalapok/i},
  {path: "/exams/editor", text: /Új vizsga/i},
  {path: "/logistics", text: /Flotta és ellátás/i},
  {path: "/logistics?tab=fleet", text: /Marked Ford Explorer/i},
  {path: "/logistics?tab=fleet&view=reviews", text: /Nincs ellenőrzésre váró forgalmi/i},
  {path: "/logistics?tab=fleet&view=warnings", text: /Jármű-hibapontok/i},
  {path: "/logistics?tab=fleet&view=tuning", text: /hivatalos tuning/i},
  {path: "/logistics/fleet/v1", text: /Kulcsosok/i},
  {path: "/finance", text: /Költségtérítések/i},
  {path: "/finance?tab=payroll", text: /Hónap lezárása/i},
  {path: "/finance?tab=settings", text: /Rendfokozat/i},
  {path: "/finance?tab=overview", text: /Havi kiadások/i},
  {path: "/profile", text: /Személyi Akta/i},
  {path: "/calculator", text: /kalkulátor|büntető/i},
  {path: "/academy", text: /Trainee akadémia/i},
  {path: "/academy?course=basic&day=1", text: /még nincs tananyag/i},
  {path: "/academy?course=qual_AB", text: /Ebben a tananyagban még nincs oldal/i},
  {path: "/events", text: /Nincs tervezett esemény/i},
  {path: "/codes", text: /10-es kódok/i},
  {path: "/codes?tab=callsign", text: /Igazoltatott jármű/i},
  {path: "/codes?tab=quiz", text: /Mit jelent|Melyik kód/i},
  {path: "/hr?tab=promotions", text: /Javaslatok/i},
  {path: "/hr?tab=trainees", text: /Most nincs Trainee/i},
  {path: "/hr?tab=duty", text: /Aktivitásfigyelő/i},
  {path: "/hr/record/u1", text: /Szolgálati lap/i},
  {path: "/mcb/informants", text: /Még nincs informátor/i},
  {path: "/policies", text: /Még nincs szabályzat/i},
  {path: "/community", text: /Még nem volt szavazás/i},
  {path: "/community?tab=ideas", text: /Ebben a nézetben nincs ötlet/i},
  // Everyone starts on their own reports; the readers' inbox (the smoke user reads it) opens with box=inbox.
  {path: "/community?tab=feedback", text: /Névtelen visszajelzés a vezetőségnek/i},
  {path: "/community?tab=feedback&box=inbox", text: /Nincs beérkezett visszajelzés/i},
  {path: "/practice", text: /Kártyacsomagok/i},
  {path: "/practice?deck=radio", text: /Mit jelent|Melyik kód/i},
  {path: "/leaderboard", text: /Szerepelek a ranglistán/i},
  {path: "/permissions", text: /Csak amit én megtehetek/i},
  {path: "/profile?tab=certificates", text: /Még nincs oklevelem/i},
  {path: "/certificates/SFSD-0000-0001", text: /Ezennel igazoljuk/i},
  {path: "/briefing", text: /Nincs aktív BOLO/i},
  {path: "/stats", text: /Leggyakoribb tételek/i},
  {path: "/mcb/organizations", text: /Még nincs nyilvántartott szervezet/i},
  {path: "/mcb/organizations/o1", text: /Hírszerzési napló/i},
  {path: "/hr?tab=bureaus", text: /Medic/i},
  {path: "/profile?tab=settings", text: /Kétlépcsős azonosítás/i},
  {path: "/mail", text: /Nincs levél ebben a mappában/i},
  {path: "/mail?box=sent&thread=t1", text: /Válasz mindenkinek/i},
  {path: "/iab", text: /Még nincs belső vizsgálat/i},
  {path: "/iab/case/c1", text: /Érintett tagok/i},
  {path: "/iab/case/c1/print", text: /Belső megjegyzésekkel/i},
  {path: "/sib", text: /Még nincs hír/i},
  {path: "/sib?tab=page", text: /Megjelenő részek/i},
  {path: "/sib?tab=gallery", text: /Még nincs kép a galériában/i},
  {path: "/sib/news/new", text: /Értesítés a tagoknak közzétételkor/i},
  {path: "/home", text: /A megye szolgálatában/i},
  {path: "/news", text: /Még nincs megjelent hír/i},
  {path: "/news/proba", text: /Csütörtök éjjel/i},
  {path: "/contact", text: /Írj a/i},
  {path: "/contact?view=track", text: /Add meg a követőkódot/i},
  {path: "/mcb/graph", text: /Kezdd egy névvel/i},
  {path: "/mcb/graph?node=person%3Ap1", text: /Kapcsolatok \(1\)/i},
  {path: "/finance/payslip/2026-09", text: /Fizetési papír/i},
  {path: "/hr/award/ribbon/r1", text: /Kitüntetési okirat/i},
  {path: "/hr/award/commendation/c1", text: /Dicsérő oklevél/i},
  {path: "/stats", text: /adatbázis-tárhely/i},
  {path: "/mcb/trash", text: /Kikötői fegyverek/i},
  {path: "/hr?tab=reviews", text: /előző: 2026 Q3/i},
  {path: "/profile?tab=reviews", text: /Még nincs értékelés/i},
];

const DOC_PERSON = {id: "u2", full_name: "Laura Graves", faction_rank: "Captain II.", badge_number: "1203"};

const SITE_ARTICLE = {id: "n1", slug: "proba", title: "Próba hír", excerpt: null, cover_url: null, category: "news", featured: false,
  published_at: "2026-10-07T08:00:00Z", author_display: "Sheriff's Information Bureau"};
const IAB_PERSON = {id: "u2", full_name: "Laura Graves", faction_rank: "Deputy Sheriff II.", badge_number: "1203", avatar_url: null, iab_title: null};

const EMPTY_TOTALS = {tickets: 0, arrests: 0, fines: 0, jail_minutes: 0, reports: 0, bolos: 0, bolos_resolved: 0, cases_opened: 0,
  cases_closed: 0, warrants: 0};

test("every page renders without runtime errors", async ({page}) => {
  test.setTimeout(90_000);
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(`${page.url()}: ${error.message}`));

  await mockSupabase(page, {
    tables: {
      profiles: [testProfile({
        faction_rank: "Commander",
        system_role: "admin",
        division: "MCB",
        division_rank: "Investigator III.",
        is_bureau_manager: true,
        qualifications: ["TB"],
      })],
      payroll_settings: [{id: "global", rank_pay: {}, unit_pay: {}, duty_tiers: [], min_duty_hours: 30, top_duty_pay: [0, 0, 0],
        top_report_pay: [0, 0, 0], report_pay: 0, picture_pay: 0, training_pay: 0, tax_percent: 3, executive_unit: "BM", updated_at: null}],
      fleet_categories: [{id: "explorer", name: "Marked Ford Explorer", description: null, unit: null, min_rank: null, tone: "orange",
        sort_order: 20}],
      fleet_vehicles: [{
        id: "v1", plate: "SFSD-012", model: "Ford Explorer", category_id: "explorer", game_id: 250562, station: "Downtown",
        callsign: null, license_name: null, capacity: 2, shared_label: null, allowed_units: null, min_rank: null, is_unmarked: true,
        registration_required: true, registration_expires_on: null, notes: null, is_active: true,
        created_at: "2026-10-01T00:00:00Z", updated_at: "2026-10-01T00:00:00Z", holders: [],
      }],
    },
    rpc: {
      get_exam_hub: {server_now: "2026-10-01T00:00:00Z", exams: [], mine: [], queue: [], live: []},
      get_academy_overview: {
        viewer: {instructor: true, trainee: false}, today: "2026-10-02", cycle: {id: "c1", start_date: "2026-10-01", status: "active"},
        basic: [1, 2, 3, 4, 5].map((day) => ({day, pages: 0})),
        courses: [{id: "qual_AB", title: "AB képesítés", description: null, category: "qualification", is_open: true, required_rank: null,
          linear_progression: true, pages: 0, completed: 0, readable: true, rank_ok: true}],
      },
      get_payroll: (args: {_month: string}) => ({
        month: args._month, status: "open", saved: false, withdrawn: null, note: null, closed_at: null, closed_by_name: null, rows: [],
        settings: {rank_pay: {}, unit_pay: {}, duty_tiers: [], min_duty_hours: 30, top_duty_pay: [0, 0, 0], top_report_pay: [0, 0, 0],
          report_pay: 0, picture_pay: 0, training_pay: 0, tax_percent: 3, executive_unit: "BM"},
        total: 0, tax: 0, paid_total: 0, can_edit_settings: true, months: [],
      }),
      get_case_list: [],
      get_events: [],
      get_mcb_overview: {
        viewer: {is_lead: true},
        totals: {open: 0, closed: 0, archived: 0, critical: 0, opened_30d: 0, closed_30d: 0, avg_close_days: null, warrants_pending: 0,
          warrants_active: 0, wanted: 0, suspects: 0},
        monthly: [{month: "2026-10", opened: 0, closed: 0}], categories: [], members: [], unattended: [], recent: [],
      },
      get_finance_overview: {pending: {count: 0, amount: 0}, months: [{month: "2026-10-01", reimbursed: 0, reimbursements: 0, payroll_status: null,
        payroll_total: null, payroll_withdrawn: null, payroll_tax_percent: null}]},
      get_promotion_board: {criteria: [], exams: [], can_edit_criteria: true, members: [], nominations: []},
      get_trainees: [],
      get_activity_watch: {months: ["2026-09-01", "2026-08-01"], recorded: [false, false], min_minutes: 1800, members: []},
      get_service_record: {
        generated_at: "2026-10-06T10:00:00Z", generated_by: "Teszt",
        member: {id: "u1", full_name: "Teszt Elek", badge_number: "1001", faction_rank: "Commander", division: "TSB", division_rank: null,
          qualifications: ["TB"], avatar_url: null, is_bureau_manager: true, is_bureau_commander: false, commanded_divisions: [],
          created_at: "2025-01-01T00:00:00Z", last_promotion_date: null},
        details: null, history: [], awards: [], records: [], duty: [], reports: [], attendance: {attended: 0, total: 0}, exams: [], certificates: [],
      },
      get_informants: {is_lead: true, informants: []},
      get_policies: {can_edit: true, members: 1, policies: []},
      get_polls: [],
      get_suggestions: {can_respond: true, suggestions: []},
      get_my_feedback: {blocked_until: null, sent_this_week: 0, reports: []},
      get_feedback_inbox: [],
      get_practice_overview: {decks: {}, streak: 0, best_streak: 0, today: "2026-10-06", days: [], can_edit: true, scenarios: [], certificates: 0},
      get_leaderboard: {month: "2026-10-01", visible: false, participants: 0,
        categories: ["duty", "reports", "events", "practice"].map((key) => ({key, entries: [], me: null}))},
      get_my_certificates: [],
      get_briefing: {generated_at: "2026-10-07T08:00:00Z", bolos: [], resolved: [], wanted: [], events: [], announcements: [],
        last24h: {tickets: 0, arrests: 0, reports: 0}},
      get_department_stats: {days: 30, from: "2026-09-07T00:00:00Z", to: "2026-10-07T00:00:00Z", unit: "week", current: EMPTY_TOTALS,
        previous: EMPTY_TOTALS, series: [{start: "2026-09-28", tickets: 0, arrests: 0, fines: 0, reports: 0}], offenses: [], heatmap: []},
      get_organizations: [],
      get_organization: {
        organization: {id: "o1", name: "Grove Street Families", kind: "gang", status: "active", threat: "high", color: "#16a34a", logo_url: null,
          territory: "Ganton", description: null, created_at: "2026-10-01T10:00:00Z", updated_at: "2026-10-01T10:00:00Z",
          created_by_name: "Teszt", updated_by_name: null, can_delete: true},
        members: [], notes: [], cases: [], vehicles: [], properties: [], warrants: [],
      },
      get_bureau_catalog: {
        ranks: [
          {id: "r1", division: "SEB", name: "Operator III.", sort_order: 1, privileged: false},
          {id: "r2", division: "SEB", name: "Operator II.", sort_order: 2, privileged: false},
          {id: "r3", division: "MCB", name: "Investigator III.", sort_order: 1, privileged: true},
        ],
        titles: [{id: "t1", division: "SEB", name: "Medic", icon: "heart-pulse", tone: "rose", description: null, sort_order: 1}],
      },
      get_mailbox: [],
      get_mail_directory: {me: {address: "john.doe@sfsd.org", name: "John Doe"}, can_broadcast: true, can_external: true, offices: [],
        groups: [{key: "all", address: "all@sfsd.org", label: "Teljes állomány", allowed: true}], members: []},
      get_mail_thread: {
        thread: {id: "t1", subject: "Tájékoztatás", created_at: "2026-10-07T08:00:00Z", last_message_at: "2026-10-07T08:00:00Z", message_count: 1,
          broadcast: true, iab: false, unread: false, last: null, to: ["all@sfsd.org"]},
        can_reply: true, recipients: [{address: "all@sfsd.org", user_id: null, group: "all"}], iab_staff: null, cases: [],
        messages: [{id: "m1", sender_name: "Harvey Cooper", sender_address: "cmd.cooper@lspd.org", sender_kind: "external", to: ["all@sfsd.org"],
          body: "Tisztelt Kollégák!", created_at: "2026-10-07T08:00:00Z", author: null}],
      },
      get_iab_overview: {viewer: {iab_title: null, is_lead: true, is_member: false}, members: [], cases: [],
        stats: {open: 0, closed_90d: 0, inbox_unread: 0}},
      get_iab_case: {
        case: {id: "c1", case_number: "IAB-2026-001", title: "Panasz", summary: "Rövid összefoglaló.", status: "open", priority: "normal",
          outcome: null, closure: null, opened_at: "2026-10-07T08:00:00Z", updated_at: "2026-10-07T08:00:00Z", closed_at: null,
          lead: null, opened_by: IAB_PERSON, closed_by: null},
        people: [{user_id: "u2", role: "complainant", note: null, added_at: "2026-10-07T08:00:00Z", person: IAB_PERSON}],
        entries: [{id: "e1", kind: "memo", title: "Értesítés", body: "Tisztelt Deputy!", created_at: "2026-10-07T08:00:00Z",
          updated_at: "2026-10-07T08:00:00Z", author: IAB_PERSON, can_edit: true}],
        mail: [], can_edit: true, can_close: true,
      },
      get_site_editor: {content: {}, updated: {}, leaders: [{id: "u9", full_name: "Admin", faction_rank: "Commander", avatar_url: null, tier: 0, hidden: true}], posts: []},
      get_public_site: {content: {hero: {title: "A megye szolgálatában."}}, news: [SITE_ARTICLE], stats: null, leadership: null,
        recruitment: {open: false}, alert_level: "normal"},
      get_public_news: [],
      get_news_post: {post: {...SITE_ARTICLE, status: "published", updated_at: "2026-10-07T08:00:00Z",
        body: [{type: "paragraph", content: [{type: "text", text: "Csütörtök éjjel közös akció volt.", styles: {}}]}]}, newer: null, older: null, related: []},
      get_relationship_graph: {center: "person:p1", truncated: false,
        nodes: [{key: "person:p1", kind: "person", id: "p1", label: "Tony Montana", status: "wanted"},
          {key: "plate:5F4821", kind: "plate", label: "SF-4821", title: "Sultan"}],
        edges: [{source: "person:p1", target: "plate:5F4821", label: "Sultan"}]},
      search_graph_nodes: [],
      get_payslip_document: {month: "2026-09-01", paid: true, paid_at: "2026-10-03T19:00:00Z", closed_at: "2026-10-02T18:00:00Z", closed_by: DOC_PERSON,
        member: {...DOC_PERSON, id: "u1", full_name: "Teszt Elek"}, tax_percent: 3,
        row: {name: "Teszt Elek", rank: "Commander", division: "TSB", unit: "BM", qualification: "TB", duty_minutes: 3125, reports: 14, pictures: 3, trained: 2,
          top_duty: 1, top_report: 2, bonus: 250000, bonus_note: "Szervezés", account_number: "SF-1",
          pay: {rank: 9000000, duty: 1500000, unit: 2000000, qualification: 1000000, reports: 7000000, pictures: 300000, training: 2000000, top_duty: 1500000,
            top_report: 1000000, bonus: 250000}, total: 25550000}},
      get_award_document: (args: {_kind: string}) => ({kind: args._kind, id: "r1", number: "R1R1R1R1",
        title: args._kind === "ribbon" ? "Szolgálati Érdemérem" : "Kiemelkedő helytállás", text: "Kiemelkedő szolgálatért", color: "#d4af37", image_url: null,
        date: "2026-10-01T10:00:00Z", member: {...DOC_PERSON, id: "u1", full_name: "Teszt Elek", division: "TSB"}, issuer: DOC_PERSON,
        head: {...DOC_PERSON, id: "u9", full_name: "Lisa Clark", title: "Bureau Manager"}}),
      get_case_trash: [{id: "c9", case_number: "SD-001/001/261001", title: "Kikötői fegyverek", status: "open", priority: "high", owner_id: "u2",
        owner_name: "Laura Graves", deleted_at: "2026-10-06T10:00:00Z", deleted_by_name: "Laura Graves", purge_at: "2026-11-05T10:00:00Z",
        evidence: 1, people: 2, warrants: 0}],
      get_review_overview: {period: "2026-Q4", current_period: "2026-Q4", members: [{user_id: "u2", full_name: "Laura Graves",
        faction_rank: "Deputy Sheriff II.", badge_number: "1203", avatar_url: null, division: "TSB", can_write: true, review: null,
        last: {period: "2026-Q3", overall: 4, status: "acknowledged"}}]},
      get_reviews: {can_write: false, current_period: "2026-Q4", reviews: []},
      get_db_health: {bytes: 30 * 1024 * 1024, limit_bytes: 500 * 1024 * 1024, measured_at: "2026-10-07T03:00:00Z",
        largest: [{table: "public.cases", bytes: 1024 * 1024}]},
      verify_certificate: {code: "SFSD-0000-0001", kind: "exam", ref: null, title: "Deputy I. vizsga", subtitle: "Sikeres vizsga",
        issued_at: "2026-10-01T10:00:00Z", valid: true, revoked_at: null, holder: {full_name: "Teszt Elek", badge_number: "1001", faction_rank: "Commander"}},
    },
  });
  await login(page);
  await expect(page).toHaveURL(/\/dashboard$/);

  for (const route of ROUTES) {
    await page.goto(route.path);
    await expect(page.getByText(route.text).first(), route.path).toBeVisible();
    await expect(page.getByText("Váratlan hiba történt"), route.path).toHaveCount(0);
  }

  expect(errors).toEqual([]);
});
