-- =============================================================================
-- The MCB's two official case files (from its Word templates) as starting documents, on top of
-- the list: "MCB Investigative File" and "Operation Safe Street File". Both start with the
-- letterhead block (logos served by the app from /public/brand, nothing stored here) and use the
-- {{ügyszám}} / {{létrehozta}} / {{dátum}} placeholders (filled by private.fill_case_template_tokens).
--
-- POST-DEPLOY: the deployed frontend before this release does not know the letterhead block
-- (BlockNote throws on an unknown block type), so apply this only after the new frontend is live:
--   1. move this file to supabase/migrations/
--   2. bunx supabase db push --db-url "<session pooler URL>"
-- Same content as src/lib/case-templates-builtin.ts (the leadership's "Alapsablonok
-- visszaállítása" adds them too). Skips a template that already exists under the same name.
-- =============================================================================

insert into public.case_templates (kind, label, description, icon, aliases, blocks, sort_order)
select v.kind, v.label, v.description, v.icon, v.aliases::text[], v.blocks::jsonb, v.sort_order
from (values
  ('document', 'MCB Investigative File', 'Az MCB hivatalos aktája fejléccel: ügyszám, létrehozó, közreműködők, tárgy és az első bejegyzés.', 'scroll', '{}', $json$[{"type":"letterhead","props":{"left":"","right":"mcb","title":"Major Crime’s Bureau","subtitle":"Detective Division","address":"San Fierro, Downtown 1257"},"children":[]},{"type":"paragraph","props":{"textColor":"default","backgroundColor":"default","textAlignment":"left"},"content":[{"type":"text","text":"Ügyszám: ","styles":{}},{"type":"text","text":"{{ügyszám}}","styles":{}}],"children":[]},{"type":"paragraph","props":{"textColor":"default","backgroundColor":"default","textAlignment":"left"},"content":[{"type":"text","text":"Létrehozta: ","styles":{}},{"type":"text","text":"{{létrehozta}}","styles":{}},{"type":"text","text":"   Közreműködött: ","styles":{}},{"type":"text","text":"xy személy","styles":{"italic":true,"textColor":"gray"}}],"children":[]},{"type":"paragraph","props":{"textColor":"default","backgroundColor":"default","textAlignment":"left"},"content":[{"type":"text","text":"Tárgy: ","styles":{}},{"type":"text","text":"nyomozás tárgya","styles":{"italic":true,"textColor":"gray"}}],"children":[]},{"type":"paragraph","props":{"textColor":"default","backgroundColor":"default","textAlignment":"left"},"content":[],"children":[]},{"type":"paragraph","props":{"textColor":"default","backgroundColor":"default","textAlignment":"left"},"content":[{"type":"text","text":"{{dátum}}, ","styles":{"bold":true}},{"type":"text","text":"cím","styles":{"bold":true,"italic":true,"textColor":"gray"}}],"children":[]},{"type":"paragraph","props":{"textColor":"default","backgroundColor":"default","textAlignment":"left"},"content":[],"children":[]}]$json$, 1),
  ('document', 'Operation Safe Street File', 'Bandaügyek aktája az Operation Safe Street (GANGS) fejlécével.', 'shield', '{}', $json$[{"type":"letterhead","props":{"left":"gangs","right":"mcb","title":"Major Crime’s Bureau","subtitle":"Detective Division","address":"San Fierro, Downtown 1257"},"children":[]},{"type":"paragraph","props":{"textColor":"default","backgroundColor":"default","textAlignment":"left"},"content":[{"type":"text","text":"Ügyszám: ","styles":{}},{"type":"text","text":"{{ügyszám}}","styles":{}}],"children":[]},{"type":"paragraph","props":{"textColor":"default","backgroundColor":"default","textAlignment":"left"},"content":[{"type":"text","text":"Létrehozta: ","styles":{}},{"type":"text","text":"{{létrehozta}}","styles":{}}],"children":[]},{"type":"paragraph","props":{"textColor":"default","backgroundColor":"default","textAlignment":"left"},"content":[{"type":"text","text":"Közreműködött: ","styles":{}}],"children":[]},{"type":"paragraph","props":{"textColor":"default","backgroundColor":"default","textAlignment":"left"},"content":[{"type":"text","text":"Tárgy: ","styles":{}}],"children":[]},{"type":"paragraph","props":{"textColor":"default","backgroundColor":"default","textAlignment":"left"},"content":[],"children":[]}]$json$, 2)
) as v(kind, label, description, icon, aliases, blocks, sort_order)
where not exists (select 1 from public.case_templates t where t.kind = v.kind and lower(btrim(t.label)) = lower(v.label));
