import {organisableAudiences} from "@/lib/events";
import {canApproveWarrants, canViewMcbOverview} from "@/lib/mcb";
import {DEMO} from "@/lib/sandbox/world/context";
import type {TrainingId} from "./catalog";
import type {TourStep, TrainingScript} from "./types";

/**
 * The steps of every training. Short on purpose: one or two sentences per step, and wherever it
 * makes sense the member does the thing (clicks, types) in the practice world instead of reading.
 */

const tour = (name: string) => `[data-tour="${name}"]`;
/** A Radix tab trigger by its value. */
const tab = (value: string) => `[role="tab"][id$="-trigger-${value}"]`;
const dialog = "[data-slot=dialog-content]";
const wide = () => window.innerWidth >= 1024;
const canOrganise = (profile: Parameters<typeof organisableAudiences>[0]) => organisableAudiences(profile).length > 0;

const CASE = DEMO.case(1);
const SHEET = DEMO.sheet(1);
const MEETING = DEMO.event(1);
const FINISH = (title: string, body: string): TourStep => ({chapter: "Kész", title, body});

const BASIC: TourStep[] = [
  {chapter: "Kezdés", title: "Üdv a gyakorló módban!", route: "/dashboard",
    body: "Most **bemutató adatokat** látsz: amit itt csinálsz, nem mentődik, és senki sem kap róla értesítést. Vágjunk bele!"},
  {chapter: "Kezdés", title: "Menü", target: [tour("nav"), tour("menu-button")], placement: "right",
    body: "A menüben éred el a modulokat (telefonon a bal felső gomb alatt). Csak azt látod, amihez a **rangod és a beosztásod** jogot ad."},
  {chapter: "Kezdés", title: "Gyorskereső", target: tour("search"), placement: "bottom",
    body: "Oldalak, kollégák és akták egy helyen. Bárhonnan megnyitod a **Ctrl + K** billentyűkkel."},
  {chapter: "Kezdés", title: "Készültségi szint", target: tour("status"), placement: "bottom",
    body: "A frakció aktuális készültsége; a színe az egész oldalon látszik. Ha vörösre vált, figyeld a hirdetményeket."},
  {chapter: "Kezdés", title: "Értesítések", target: tour("bell"), placement: "bottom", action: {type: "click", hint: "Nyisd meg: kattints a csengőre."},
    body: "Itt jelez az oldal, ha valami rád vár: elbírált kérelem, vizsgaeredmény, említés egy aktában."},
  {chapter: "Kezdés", title: "Legfrissebb értesítések", target: tour("bell-panel"), placement: "left",
    body: "Egy kattintás, és a helyszínre visz. A fogaskerékkel kategóriánként **némíthatod** őket."},
  {chapter: "Irányítópult", title: "Irányítópult", route: "/dashboard", closeOverlays: true, target: tour("dashboard-hero"), placement: "bottom",
    body: "Rangod, jelvényszámod, szolgálati időd és a készültség egy pillantásra."},
  {chapter: "Irányítópult", title: "Teendők", target: tour("dashboard-tasks"), placement: "bottom",
    body: "Csak ami most figyelmet kér: függő kérelem, lejáró forgalmi, javítandó vizsga. Kattintásra odavisz."},
  {chapter: "Irányítópult", title: "Hirdetmények", target: tour("dashboard-announcements"), placement: "left",
    body: "A vezetőség közleményei; a **kitűzöttek** mindig felül maradnak."},
  {chapter: "Irányítópult", title: "Havi követelmény", target: tour("dashboard-month"), placement: "left",
    body: "Hol tartasz a hónapban: a **jelentések** száma élőben frissül, a **duty időt** a gyűlésen rögzítik."},
  {chapter: "Irányítópult", title: "Közelgő események", target: tour("dashboard-events"), placement: "left",
    body: "A következő két hét gyűlései és képzései. A **Válaszolj** jelzi, ha még nem mondtad meg, ott leszel-e."},
  {chapter: "Irányítópult", title: "Eseménynapló", target: tour("dashboard-log"), placement: "top",
    body: "A kalkulátorból kimásolt bírságok és letartóztatások, élőben. Nézzük meg, honnan kerülnek ide!"},
  {chapter: "Kalkulátor", title: "Büntető kalkulátor", target: tour("nav-calculator"), placement: "right", when: wide,
    action: {type: "click", hint: "Kattints a Büntető kalkulátor menüpontra."}, body: "Nyisd meg a menüből!"},
  {chapter: "Kalkulátor", title: "Keresés", route: "/calculator", closeOverlays: true, target: tour("calc-search"), placement: "bottom", interactive: true,
    action: {type: "wait", hint: "Írj be legalább 3 betűt.",
      done: () => (document.querySelector<HTMLInputElement>(`${tour("calc-search")} input`)?.value.trim().length ?? 0) >= 3},
    body: "Név, rövidítés vagy paragrafus szerint keres. Írd be például: **ittas**"},
  {chapter: "Kalkulátor", title: "Tétel hozzáadása", target: [tour("calc-add"), tour("calc-list")], placement: "left", interactive: true,
    action: {type: "wait", hint: "Adj hozzá egy tételt (a csoportokat kattintással nyitod ki).",
      done: () => [...document.querySelectorAll("[data-cart]")].some((element) => Number(element.getAttribute("data-cart")) > 0)},
    body: "A **Hozzáad** gombbal kerül a jegyzőkönyvbe; többször is megnyomhatod."},
  {chapter: "Kalkulátor", title: "Kiszabás", target: [tour("calc-sentence"), tour("calc-drawer")], placement: "left",
    body: "A bírság és a fegyház a tételekből számolódik; a csúszkával a sávon belül állítod. A **/ticket** és az **/arrest** parancsot egy kattintással másolod."},
  {chapter: "Kalkulátor", title: "Jelentés a tételekből", target: [tour("calc-report"), tour("calc-drawer")], placement: "left",
    action: {type: "click", hint: "Kattints a Jelentés készítése gombra."},
    body: "A kalkulátor átadja a vádpontokat, a bírságot és a fegyházat a jelentésírónak. Próbáld ki!"},
  {chapter: "Jelentések", title: "Jelentésíró", route: "/reports", closeOverlays: true, target: tour("report-form"), placement: "right",
    body: "A fórum kötelező sablonja: kitöltöd, és kész BBCode-ot másolsz a fórumra. A kalkulátorból átvitt tételek maguktól bekerülnek."},
  {chapter: "Jelentések", title: "Kitöltés képről", target: tour("report-scan"), placement: "bottom",
    body: "A tablet **Polgárok** oldaláról készült képből kiolvassuk a nevet és az igazolványszámokat. A kép nem kerül fel sehova; az eredményt mindig ellenőrizd."},
  {chapter: "Jelentések", title: "Előnézet és rögzítés", target: tour("report-output"), placement: "left",
    body: "Így néz majd ki a fórumon. Ha kiraktad, itt rögzíted: a havi jelentésszám a **fizetésedbe** számít."},
  {chapter: "Logisztika", title: "Járműigénylés", route: "/logistics", target: tour("page-actions"), placement: "bottom",
    body: "Szolgálati járművet itt igényelsz; az elbírálásról értesítést kapsz."},
  {chapter: "Logisztika", title: "Igényléseid", target: tour("logistics-requests"), placement: "top",
    body: "Minden igénylés állapota: függőben, elfogadva, vagy elutasítva indoklással."},
  {chapter: "Logisztika", title: "Járműpark", target: tour("logistics-tab-fleet"), placement: "bottom",
    action: {type: "click", hint: "Kattints a Járműpark fülre."}, body: "Nézzük a flottát!"},
  {chapter: "Logisztika", title: "Járművek és kulcsok", route: "/logistics?tab=fleet", target: tour("fleet-list"), placement: "top",
    body: "Látod, kinél van kulcs. A **forgalmi lejártát** is itt követed: megújításhoz elég egy képernyőkép a játékból."},
  {chapter: "Pénzügy", title: "Költségtérítés", route: "/finance", target: tour("page-actions"), placement: "bottom",
    body: "Szolgálati kiadásod (javítás, üzemanyag) megtérítését itt kéred, bizonylattal."},
  {chapter: "Pénzügy", title: "Fizetéseid", target: tab("payroll"), placement: "bottom",
    body: "A havi fizetésed tételesen: rang, duty idő, jelentések, képesítések."},
  {chapter: "Oktatás", title: "Akadémia", route: "/academy", target: tour("academy-catalog"), placement: "top",
    body: "Tananyagok a képzésekhez és a képesítésekhez; amit elolvastál, megjelöljük."},
  {chapter: "Oktatás", title: "Vizsgaközpont", route: "/exams", target: tour("exam-catalog"), placement: "top",
    body: "Itt indítod a vizsgáidat. Az időzítő a szerveren fut, az eredményről értesítést kapsz."},
  {chapter: "Események", title: "Események", route: "/events", target: tour("events-list"), placement: "top",
    body: "Gyűlések, képzések és vizsganapok. Az új eseményekről értesítést kapsz, és az esemény napján emlékeztetőt."},
  {chapter: "Események", title: "Ott leszel?", target: `#event-${MEETING} ${tour("event-rsvp")}`, placement: "bottom",
    action: {type: "click", hint: "Jelezd, hogy ott leszel a gyűlésen."},
    body: "Egy kattintás: **Ott leszek**, **Talán** vagy **Nem tudok menni**. A szervező látja, kire számíthat."},
  {chapter: "Személyügy", title: "Kik a vezetők?", route: "/hr", target: tour("hr-leaders"), placement: "bottom",
    body: "Az iroda, a divíziók és az alegységek vezetői egy helyen: egy egységgel kapcsolatban hozzájuk fordulj."},
  {chapter: "Eszközök", title: "Kódtár", route: "/codes", target: tour("codes-search"), placement: "bottom", interactive: true,
    body: "Minden rádiókód egy helyen, kereséssel és másolással. A **Gyakorlás** fülön kvízzel tanulhatod őket."},
  {chapter: "Profil", title: "Profilod", route: "/profile", target: tour("profile-card"), placement: "left",
    body: "Szolgálati igazolványod, duty időd, járműveid és fegyelmid. Szabadságot is innen kérsz."},
  {chapter: "Profil", title: "Képzések", target: tab("trainings"), placement: "bottom", action: {type: "click", hint: "Kattints a Képzések fülre."},
    body: "Ezt a képzést és a rangodhoz tartozó többit innen **bármikor újrajátszhatod**."},
  {chapter: "Profil", title: "Képzéseid", target: tour("profile-trainings"), placement: "top",
    body: "A zárolt képzések akkor nyílnak meg, amikor új rangot vagy beosztást kapsz; ilyenkor maguktól elindulnak."},
  FINISH("Ennyi volt!", "Ha elakadsz, a **Ctrl + K** gyorskeresőből mindent elérsz. Jó szolgálatot!"),
];

const MCB: TourStep[] = [
  {chapter: "Nyomozó Iroda", title: "Nyomozó Iroda", route: "/mcb", target: tour("mcb-nav"), placement: "bottom",
    body: "Az MCB saját menüje: **Akták**, **Nyilvántartás**, **Parancsok**, és a vezetőknek **Vezetés**."},
  {chapter: "Akták", title: "Aktalista", target: tour("mcb-cases"), placement: "top",
    body: "Minden akta: állapot, prioritás, felelős, bizonyítékok és parancsok. Felül szűrsz és keresel, a keresés az akták szövegében is talál."},
  {chapter: "Akták", title: "Új akta", target: tour("mcb-new-case"), placement: "bottom",
    body: "Sablonból indul (nyomozati akta, helyszíni szemle, kihallgatás): a dokumentum váza kész."},
  {chapter: "Akták", title: "Nyissunk meg egyet", target: `${tour("mcb-case")}[data-case-id="${CASE}"]`, placement: "bottom",
    action: {type: "click", hint: "Kattints a „Fegyvercsempészet a kikötőben” aktára."}, body: "Ez a gyakorló akta, te is szerkesztheted."},
  {chapter: "Az akta", title: "Fejléc", route: `/mcb/case/${CASE}`, target: tour("case-header"), placement: "bottom",
    body: "Szám, állapot, prioritás, felelős; jobbra a műveletek: lezárás, átadás, nyomtatás."},
  {chapter: "Az akta", title: "Közös dokumentum", target: tour("case-editor"), placement: "left", interactive: true,
    body: "Többen írhatjátok egyszerre. **20 másodperc** csend után magától ment, és szól, ha közben más mentett. Írj bele valamit!"},
  {chapter: "Az akta", title: "Bizonyíték és említés", target: tour("case-editor"), placement: "left", interactive: true,
    body: "A **/** jellel bizonyítékot vagy kész blokkot szúrsz be, a **@** jellel kollégát, személyt vagy aktát említesz; a kolléga értesítést kap."},
  {chapter: "Az akta", title: "Mentés", target: tour("case-save"), placement: "bottom",
    body: "Itt látod, mentve van-e. A **Ctrl + S** azonnal ment."},
  {chapter: "Az akta", title: "Személyek és csapat", target: tour("case-rail"), placement: "right", when: wide,
    body: "Gyanúsítottak, tanúk, sértettek az aktához kötve; a nevükre kattintva megnyílik a dosszié. Alatta a csapat és a jogosultságok."},
  {chapter: "Az akta", title: "Bizonyítékok, parancsok, üzenetek, napló", target: tour("case-tabs"), placement: "left", when: wide,
    body: "A feltöltött fájlok, a parancsok, a nyomozók csevegése és az akta naplója, ahol minden változás látszik."},
  {chapter: "Az akta", title: "Parancsok", target: tour("case-tab-warrants"), placement: "left", when: wide,
    action: {type: "click", hint: "Kattints a Parancsok fülre."}, body: "Nézzük a parancsokat!"},
  {chapter: "Az akta", title: "Parancskérelem", target: tour("case-warrants"), placement: "left", when: wide,
    body: "Elfogató vagy házkutatási parancsot kérhetsz; jóváhagyás után az elfogatóval a személy **körözött** lesz."},
  {chapter: "Nyilvántartás", title: "Körözési lista", route: "/mcb/suspects", target: [tour("suspects-wanted"), tour("suspects-list")], placement: "bottom",
    body: "A körözött személyek plakátjai: egy kattintás, és megnyílik a dossziéjuk."},
  {chapter: "Nyilvántartás", title: "Bűnügyi nyilvántartás", target: tour("suspects-list"), placement: "top",
    body: "Minden személy dossziéja: járművek, ingatlanok, kapcsolatok, akták és parancsok egy helyen."},
  {chapter: "Parancsok", title: "Parancsok", route: "/mcb/warrants", target: [tour("warrants-list"), tour("warrants-filters")], placement: "top",
    body: "Az összes parancs állapota. A jóváhagyók innen döntenek; saját kérelmet senki sem bírálhat el."},
  {chapter: "Parancsok", title: "Jóváhagyás", target: [tour("warrants-list"), tour("warrants-filters")], placement: "top", interactive: true,
    when: (profile) => canApproveWarrants(profile),
    body: "Te jóváhagyhatsz. Nézd meg az indoklást és a bizonyítékokat; próbáld ki a **Jóváhagyás** gombot, itt nem élesedik."},
  {chapter: "Vezetés", title: "Az iroda vezetése", route: "/mcb/admin", target: tour("mcb-overview"), placement: "bottom", when: (profile) => canViewMcbOverview(profile),
    body: "Statisztikák, a nyomozók terhelése és a gazdátlan akták egy oldalon."},
  FINISH("Kész!", "Bátran nyiss aktát: a dokumentum, a csevegés és a parancsok mind ugyanazon az oldalon vannak."),
];

const SUPERVISOR: TourStep[] = [
  {chapter: "Személyügy", title: "Személyügy", route: "/hr", target: tour("hr-tabs"), placement: "bottom",
    body: "Az állomány, a szolgálati idők, a kérelmek, a kilépettek és minden változás története."},
  {chapter: "Személyügy", title: "Egy tag adatlapja", target: `${tour("hr-member")}[data-member-id="${DEMO.person(11)}"]`, placement: "top",
    action: {type: "click", hint: "Kattints Kitalált Kristófra."}, body: "Nyisd meg egy tag adatlapját!"},
  {chapter: "Személyügy", title: "Rendfokozat", target: tour("member-rank"), placement: "left",
    body: "Egy kattintással léptetsz fel vagy le, a rangod által megengedett sávban. A tag értesítést kap, és bekerül a történetébe."},
  {chapter: "Személyügy", title: "Feljegyzések", target: tab("records"), placement: "left", action: {type: "click", hint: "Kattints a Feljegyzések fülre."},
    body: "Figyelmeztetés, dicséret, belső jegyzet."},
  {chapter: "Személyügy", title: "Figyelmeztetés, dicséret", target: tour("member-records"), placement: "left", interactive: true,
    body: "A nálad alacsonyabb rangúaknak rögzíthetsz. Három aktív jármű-hibapont magától figyelmeztetéssé válik."},
  {chapter: "Személyügy", title: "Kérelmek", closeOverlays: true, target: tour("hr-tab-requests"), placement: "bottom",
    body: "Új regisztrációk és szabadságkérelmek elbírálása; a számuk az irányítópulton is megjelenik."},
  {chapter: "Személyügy", title: "Szolgálati idő", target: tour("hr-tab-duty"), placement: "bottom",
    body: "A havi duty időt itt rögzíted (pl. **95:48**), vagy a **Képekből** gombbal a UCP taglistájáról olvastatod be; ebből számol a fizetés."},
  {chapter: "Vizsgák", title: "Javításra vár", route: "/exams?tab=grading", target: tour("grading-sheet"), placement: "top",
    action: {type: "click", hint: "Kattints a Javítás gombra."}, body: "A beadott vizsgalapok. Nyisd meg az elsőt!"},
  {chapter: "Vizsgák", title: "Pontozás", route: `/exams/grading/${SHEET}`, target: `#sheet-question-de-q3`, placement: "right", interactive: true,
    body: "A feleletválasztósakat a rendszer pontozza. A kifejtősnél te adod a pontot; a **javítási útmutató** segít."},
  {chapter: "Vizsgák", title: "Vizsganapló", target: tour("grading-integrity"), placement: "left",
    body: "Tények a vizsga közbeni eseményekről: ablakváltás, beillesztés. Nem vád, csak segít a döntésben."},
  {chapter: "Vizsgák", title: "Döntés", target: tour("grading-decision"), placement: "left", interactive: true,
    body: "Sikeres vagy sikertelen; a vizsgázó értesítést kap, és ha engeded, látja a javítást is."},
  {chapter: "Logisztika", title: "Járműigénylések", route: "/logistics", target: tour("request-decide"), placement: "bottom", interactive: true,
    body: "A függő igényléseket te bírálod el. Jóváhagyáskor a járműparkból választasz, és a kulcs automatikusan a kérelmezőé lesz. Próbáld ki!"},
  {chapter: "Logisztika", title: "Forgalmi ellenőrzés és hibapontok", route: "/logistics?tab=fleet", target: tour("fleet-views"), placement: "bottom",
    body: "Ha a gép nem tudta elolvasni a forgalmi képét, itt döntesz róla. A **Hibapont** gombbal szabálytalan járműhasználatot rögzítesz."},
  {chapter: "Jelentések", title: "Havi összesítő", route: "/reports?tab=summary", target: tour("reports-summary"), placement: "top",
    body: "Ki hány jelentést rögzített a hónapban; tag nevében is rögzíthetsz."},
  {chapter: "Események", title: "Esemény szervezése", route: "/events", target: tour("event-new"), placement: "bottom", when: canOrganise,
    body: "Gyűlést, képzést vagy vizsganapot itt hirdetsz meg. Az érintettek értesítést kapnak, a jelentkezőket az esemény kártyáján látod."},
  FINISH("Kész!", "A vezetői teendőidet az irányítópult **Teendők** sávja mindig összegyűjti."),
];

const INSTRUCTOR: TourStep[] = [
  {chapter: "Akadémia", title: "Tananyagok", route: "/academy", target: tour("academy-course-qual_SAHP"), placement: "bottom",
    action: {type: "click", hint: "Nyisd meg az SAHP tananyagot."}, body: "Oktatóként szerkesztheted a tananyagokat. Nézzünk meg egyet!"},
  {chapter: "Akadémia", title: "Oldalak", route: "/academy?course=qual_SAHP", target: tour("material-pages"), placement: "right",
    body: "A tananyag oldalakból áll. Szerkesztés közben itt adsz hozzá oldalt, és itt rendezed őket."},
  {chapter: "Akadémia", title: "Szerkesztés", target: tour("material-edit"), placement: "bottom", action: {type: "click", hint: "Kattints a Szerkesztés gombra."},
    body: "Kapcsold be a szerkesztést!"},
  {chapter: "Akadémia", title: "Írj bele!", target: ".bn-container", placement: "left", interactive: true,
    body: "Úgy írsz, mint egy szövegszerkesztőben; a **/** jellel blokkot szúrsz be. A beillesztett képeket a mentéskor feltöltjük."},
  {chapter: "Akadémia", title: "Alapképzés", route: "/academy?course=basic", closeOverlays: true, target: tab("log"), placement: "bottom",
    action: {type: "click", hint: "Kattints a Napló fülre."}, body: "Az újoncok 5 napos képzése; a napok a turnus kezdetétől nyílnak meg. Nézzük a naplót!"},
  {chapter: "Akadémia", title: "Turnus és jelenlét", target: tour("instructor-panel"), placement: "top",
    body: "Itt indítasz turnust, veszel fel újoncot, és naponta vezeted a jelenlétet."},
  {chapter: "Vizsgák", title: "Javítás", route: "/exams?tab=grading", target: tour("grading-list"), placement: "top",
    body: "A felvételi és a Deputy I. vizsgákat oktatóként te is javítod."},
  FINISH("Kész!", "Köszönjük, hogy tanítasz!"),
];

const COMMAND: TourStep[] = [
  {chapter: "Készültség", title: "Készültségi szint", route: "/dashboard", target: tour("status"), placement: "bottom",
    action: {type: "click", hint: "Nyisd meg a menüt."}, body: "A készültséget a parancsnokság állítja; mindenki azonnal látja."},
  {chapter: "Készültség", title: "Válassz szintet", target: tour("status-menu"), placement: "left", interactive: true,
    body: "Próbáld ki nyugodtan: gyakorló módban senki sem látja. A tagfelvételt is itt nyitod és zárod."},
  {chapter: "Hirdetmények", title: "Új hirdetmény", closeOverlays: true, target: tour("announcement-new"), placement: "bottom",
    action: {type: "click", hint: "Kattints az Új hirdetmény gombra."}, body: "Közleményt írhatsz az állománynak; mindenki értesítést kap."},
  {chapter: "Hirdetmények", title: "Hirdetmény írása", target: dialog, placement: "right", interactive: true,
    body: "Típus, kiemelés, és eldöntheted, hogy a neved vagy csak a beosztásod látszik."},
  {chapter: "Személyügy", title: "Előléptetés és elbocsátás", route: "/hr", closeOverlays: true, target: tour("hr-content"), placement: "top",
    body: "**Sergeant II.**-ig léptethetsz elő. Elbocsátáskor a tag adatai a kilépettek közé kerülnek, visszavételi javaslattal."},
  {chapter: "Személyügy", title: "Kilépettek", target: tour("hr-tab-former"), placement: "bottom",
    body: "Minden távozó: ok, dátum, és hogy visszatérhet-e."},
  {chapter: "Flotta", title: "A flotta kezelése", route: "/logistics?tab=fleet", target: tour("fleet-manage"), placement: "bottom",
    body: "Új jármű, kulcsok kiosztása, hibapontok, és a **Kategóriák** gombbal a flotta csoportjai: átnevezés, új, törlés."},
  {chapter: "Pénzügy", title: "Költségtérítések", route: "/finance", target: tour("reimbursements"), placement: "top",
    body: "A kérelmeket a parancsnokság bírálja el; a bizonylatokat itt nézed meg."},
  {chapter: "Pénzügy", title: "Áttekintés", target: tab("overview"), placement: "bottom",
    body: "A havi költségtérítések és fizetések összesítve, hónapokra bontva."},
  {chapter: "Nyomozó Iroda", title: "Rálátás minden aktára", route: "/mcb", target: tour("mcb-cases"), placement: "top",
    body: "Parancsnokként minden aktát megnyithatsz, és dönthetsz a parancsokról."},
  FINISH("Kész!", "A parancsnoki eszközöket a fejléc, a Személyügy és a Pénzügy oldal fogja össze."),
];

const EXECUTIVE: TourStep[] = [
  {chapter: "Fizetés", title: "Havi fizetés", route: "/finance?tab=payroll", target: tour("payroll-table"), placement: "top",
    body: "A gyűlés után itt töltöd ki. A rendszer a duty időből, a jelentésekből és a képesítésekből számol."},
  {chapter: "Fizetés", title: "Egy tag fizetése", target: tour("payroll-member"), placement: "right",
    action: {type: "click", hint: "Kattints egy névre."}, body: "Nézzük meg egy tag részleteit!"},
  {chapter: "Fizetés", title: "Tételek", target: dialog, placement: "left", interactive: true,
    body: "Az automatikus értékeket felülírhatod (TOP helyezés, egység, képesítés); a bónuszhoz írj indoklást."},
  {chapter: "Fizetés", title: "Kassza", closeOverlays: true, target: tour("treasury"), placement: "bottom",
    body: "A frakció számlájának egyenlege: látod, mennyibe kerül a hónap, és mennyi marad utána."},
  {chapter: "Fizetés", title: "Hónap zárása", target: tour("payroll-close"), placement: "bottom",
    body: "Zárás után a tagok értesítést kapnak, és a Pénzügy oldalon látják a fizetési papírjukat."},
  {chapter: "Fizetés", title: "Fizetési tábla", route: "/finance?tab=settings", target: tour("payroll-settings"), placement: "top",
    body: "Rangonkénti bér, pótlékok, duty-sávok, adó és a havi követelmény; a Commander és az irodavezető módosíthatja."},
  {chapter: "Kitüntetések", title: "Kitüntetések", route: "/hr", target: tour("hr-content"), placement: "top",
    body: "Szalagot a tag adatlapján, a **Kitüntetések** fülön adományozhatsz."},
  FINISH("Kész!", "A pénzügyi döntések nyoma megmarad: a lezárt hónapok összegei később sem változnak."),
];

const BUREAU_COMMANDER: TourStep[] = [
  {chapter: "Egység", title: "Az egységed tagjai", route: "/hr", target: tour("hr-content"), placement: "top",
    body: "Az általad vezetett egység képesítéseit te adod és veszed el; a TSB-ből átvehetsz tagot a divíziódba."},
  {chapter: "Flotta", title: "Egységjárművek", route: "/logistics?tab=fleet", target: tour("fleet-manage"), placement: "bottom",
    body: "Az egységed járműveinek kulcsait te osztod ki a **Kiosztás** gombbal."},
  {chapter: "Akadémia", title: "Egységtananyag", route: "/academy", target: tour("academy-catalog"), placement: "top",
    body: "Az egységed tananyagát te szerkesztheted."},
  {chapter: "Vizsgák", title: "Egységvizsgák", route: "/exams", target: [tour("page-actions"), tour("exam-catalog")], placement: "bottom",
    body: "Vizsgát hozhatsz létre és szerkeszthetsz az egységednek; a beadott lapokat te javítod."},
  {chapter: "Események", title: "Egységesemény", route: "/events", target: tour("event-new"), placement: "bottom", when: canOrganise,
    body: "Képzést vagy gyakorlatot hirdethetsz az egységednek; csak az egység tagjai kapnak róla értesítést."},
  FINISH("Kész!", "Az egységed ügyei mindig a Személyügy és a Logisztika oldalon futnak össze."),
];

const BUREAU_MANAGER: TourStep[] = [
  {chapter: "Irodavezető", title: "Teljes jogkör", route: "/hr", target: tour("hr-content"), placement: "top",
    body: "Minden HR-jogosultság nálad van: parancsnokok kinevezése, bármely rang, divízió és képesítés."},
  {chapter: "Pénzügy", title: "Fizetés és fizetési tábla", route: "/finance?tab=settings", target: tour("payroll-settings"), placement: "top",
    body: "A havi fizetést és a fizetési táblát is te kezeled."},
  {chapter: "Nyomozó Iroda", title: "Az iroda vezetése", route: "/mcb/admin", target: tour("mcb-overview"), placement: "bottom",
    body: "Minden aktát látsz, archiválhatsz, és vezetheted az irodát."},
  {chapter: "Készültség", title: "Készültség és tagfelvétel", route: "/dashboard", target: tour("status"), placement: "bottom",
    body: "A készültségi szintet és a tagfelvételt is te állíthatod."},
  FINISH("Kész!", "Nagy jogkör, nagy felelősség: minden változás naplózva van."),
];

const SCRIPTS: Record<TrainingId, TourStep[]> = {
  basic: BASIC,
  mcb: MCB,
  supervisor: SUPERVISOR,
  instructor: INSTRUCTOR,
  command: COMMAND,
  executive: EXECUTIVE,
  bureau_commander: BUREAU_COMMANDER,
  bureau_manager: BUREAU_MANAGER,
};

export async function loadScript(id: TrainingId): Promise<TrainingScript> {
  return {id, steps: SCRIPTS[id]};
}
